.PHONY: all

all:
	gcc client.c -o client -L -lpthread
	gcc server.c -o server -L -lphtread

client:
	gcc client.c -o client -L -lpthread

server:
	gcc server.c -o server -L -lphtread
	
clean:
	rm -f client
	rm -f clinet.o
	rm -f server
	rm -f server.o